- name: Install & Provision Consul Cluster
  hosts: consul_servers
  become: true
  roles:
        - role: consul-cluster 
      
- name: Install & Provision Consul clients
  hosts: load_balancers
  become: true
  vars:
    client_group_name: "load_balancers"
  roles:
        - role: consul-client 

- name: Install & Provision Consul clients
  hosts: backends
  become: true
  vars:
    client_group_name: "backends"
  roles:
        - role: consul-client      