- name: Install & Provision Load Balancer for API Kubernetes  
  hosts: kub_loadbalancers_nodes
  become: true
  roles:
        - role: haproxy
        - role: keepalived
      
- name: Install & Provision Kubernetes Cluster (Master Nodes) 
  hosts: kub_master_nodes
  become: true
  roles:
        - role: kube-cluster-master

- name: Install & Provision Kubernetes Workers 
  hosts: kub_worker_nodes
  become: true
  roles:
        - role: kube-workers        
      
