#SPDX-License-Identifier: MIT-0
---
# defaults file for elastic-search
es_version: "8"
es_yandex_mirror: "https://mirror.yandex.ru/mirrors/elastic/{{ es_version }}/"

jvm_heap_size: 1   # heap size in Gb

cluster_name: "es"


