#SPDX-License-Identifier: MIT-0
---
# tasks file for haproxy
- name: Install Haproxy
  ansible.builtin.include_tasks:  install.yaml
  tags: 
     - install_haproxy
  when: ansible_facts["os_family"] == "Debian"

- name: Provision Haproxy
  block:
   - ansible.builtin.include_tasks: 
       file: provision.yaml
  tags: 
     - provision_haproxy
  when: ansible_facts["os_family"] == "Debian"