- name: Disable and stop the Postgresql service
  ansible.builtin.systemd_service:
    name: postgresql
    state: stopped
    enabled: false
  tags: always

- name: Create directory for log files
  ansible.builtin.file:
        path: /var/log/patroni
        state: directory
        owner: postgres
        group: postgres
        mode: '0755'
  tags: always

- name: Create directory for postgres in home
  ansible.builtin.file:
        path: /home/postgres/
        state: directory
        owner: postgres
        group: postgres
        mode: '0755'
  tags: always

- name: Render .pgpass_patroni template
  ansible.builtin.template:
    src: templates/.pgpass_patroni.j2
    dest: /home/postgres/.pgpass_patroni
    mode: 0600
    owner: "postgres"
    group: "postgres"    
  tags: always  


- name: Render patroni config.yml templates
  ansible.builtin.template:
    src: templates/config.yml.in.j2
    dest: /etc/patroni/config.yml.in
    mode: 0640
    owner: "postgres"
    group: "postgres"    
  tags: always  

- name: Render patroni dcs.yml templates
  ansible.builtin.template:
    src: templates/dcs.yml.j2
    dest: /etc/patroni/dcs.yml
    mode: 0640
    owner: "postgres"
    group: "postgres"    
  tags: always  

- name: Validate Patroni configuration with error details
  ansible.builtin.command: patroni --validate-config /etc/patroni/config.yml.in
  register: patroni_validation
  failed_when: patroni_validation.rc != 0
  ignore_errors: yes
  tags: always 

- name: Fail the playbook with error message
  ansible.builtin.fail:
    msg: "Patroni config validation failed: {{ patroni_validation.stderr }}"
  when: patroni_validation is failed
  tags: always

- name: Render patroni systemd unit with dynamic cluster configuration
  ansible.builtin.template:
        src: templates/patroni.service.j2
        dest: /etc/systemd/system/patroni.service
  tags: always

- name: Force systemd to reread configs
  ansible.builtin.systemd_service:
    daemon_reload: true
  tags: always

- name: Enable and start patroni service
  ansible.builtin.systemd:
        name: patroni
        state: restarted
        enabled: yes
  register: patroni_service_status
  tags: always 