#SPDX-License-Identifier: MIT-0
---
# tasks file for node-exporter
- name: Create node_exporter user
  ansible.builtin.user:
    name: node_exporter
    system: true
    shell: /bin/false
    create_home: false

- name: Download Node Exporter binary
  ansible.builtin.get_url:
    url: "{{ node_exporter_url }}"
    dest: "/tmp/node_exporter.tar.gz"
  register: download_result
  until: download_result is succeeded
  retries: 3
  delay: 5

- name: Extract Node Exporter
  ansible.builtin.unarchive:
    src: "/tmp/node_exporter.tar.gz"
    dest: "/tmp/"
    remote_src: yes

- name: Install Node Exporter binary
  ansible.builtin.copy:
    src: "/tmp/node_exporter-1.7.0.linux-amd64/node_exporter"
    dest: "/usr/local/bin/node_exporter"
    mode: '0755'
    remote_src: yes

- name: Deploy Node Exporter systemd service
  ansible.builtin.template:
    src: node_exporter.service.j2
    dest: /etc/systemd/system/node_exporter.service

- name: Start and enable Node Exporter service
  ansible.builtin.systemd:
    name: node_exporter
    state: started
    enabled: yes