#SPDX-License-Identifier: MIT-0
---
# tasks file for keepalived
- name: Install Keepalived
  ansible.builtin.include_tasks:  install.yaml
  tags: 
     - install
  when: ansible_facts["os_family"] == "Debian"

- name: Provision Keepalived
  block:
   - ansible.builtin.include_tasks: 
       file: provision.yaml
  tags: 
     - provision
  when: ansible_facts["os_family"] == "Debian"