all:
  children:
     es:
      hosts:
        lab08-es-node1:
          ansible_host: 192.168.70.61
          cluster_net_addr: 10.10.50.51
        lab08-es-node2:
          ansible_host: 192.168.70.62
          cluster_net_addr: 10.10.50.52    
        lab08-es-node3:
          ansible_host: 192.168.70.63
          cluster_net_addr: 10.10.50.53

     logstash:
       hosts:
        lab08-node-logstash:
          ansible_host:  192.168.70.65
          cluster_net_addr: 10.10.50.55   
      
     kibana:
       hosts:
         lab08-node-kibana:
           ansible_host:   192.168.70.66
           cluster_net_addr: 10.10.50.56

     kafka:
      hosts:
        lab08-kafka-node1:
          ansible_host: 192.168.70.80
          cluster_net_addr: 10.10.50.80
        lab08-kafka-node2:
          ansible_host: 192.168.70.81
          cluster_net_addr: 10.10.50.81    
        lab08-kafka-node3:
          ansible_host: 192.168.70.82
          cluster_net_addr: 10.10.50.82     
         
  vars:
      ansible_user: deploy
      ansible_connection: ssh 
      ansible_python_interpreter : /usr/bin/python3.12   